FROM eclipse-temurin:17

LABEL mentainer="Karan D"

WORKDIR /app

COPY target/springbootrestfuwebservices-0.0.1-SNAPSHOT.jar /app/springbootrestfuwebservices.jar

ENTRYPOINT ["jave","-jar","springbootrestfuwebservices.jar"]
